name = "gsurveyai"
main = "src/server.ts"
compatibility_date = "2024-06-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "CACHE"
id = "08cc84d43a784ca8a39e349e99c4702f"
preview_id = "0a3d4a11fb2f428586ad3731368762bf"

[[d1_databases]]
binding = "DB"
database_name = "gsurveyai-db"
database_id = "3282e071-24de-4c39-944f-23b25fd75cda"