name = "gsurveyai"
main = "src/server.ts"
compatibility_date = "2024-06-23"
node_compat = true

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[[d1_databases]]
binding = "DB"
database_name = "customer-happy-db"
database_id = "your-d1-database-id"

[build]
command = "npm run build"
upload_dir = "./dist"

# Custom domain configuration (add after purchasing domain)
routes = [
  { pattern = "gsurveyai.com/*", custom_domain = true },
  { pattern = "www.gsurveyai.com/*", custom_domain = true }
]